### PR TITLE
Taking the existing Indy Node.js Wrapper code as the foundation for an aries-sdk-javascript

### PR DESCRIPTION
**Pull request by ajile-in**
Taking the existing Indy Node.js Wrapper code as the foundation for an aries-sdk-javascript.

- no changes done in the Indy Node.js wrapper. Code moved as it was.
- can start doing code optimizations as suggested by @mattraffel once we discuss on the standards,  and next plan of action during our next call scheduled by @smithbk on 17th Sep.

### CODE REVIEW

**Comment by ryjones** [comment]
@smithbk @matt-raffel-kiva @esplinr please see the conversation here: https://github.com/hyperledger/aries-sdk-javascript/pull/1

**Review by ryjones — DISMISSED** [review]
Could I ask you to squash this into one commit?

**Comment by aggmoulik** [comment]
Hello sir @jadhavajay I would love to contribute in the JavaScript wrapper and I have experience in writing a plugin in typescript for salesforce oclif linter and also contributed to typescript-eslint.

**Comment by ajile-in** [comment]
> Hello sir @jadhavajay I would love to contribute in the JavaScript wrapper and I have experience in writing a plugin in typescript for salesforce oclif linter and also contributed to typescript-eslint.

Hi @moulikcipherX
Please join the discussion on Rocket Chat [here](https://chat.hyperledger.org/channel/aries-javascript).

**Comment by ajile-in** [comment]
> Could I ask you to squash this into one commit?

@ryjones I am sorry, I did not understand the purpose of it? Will two commits cause any issue in merging?

**Comment by matt-raffel-kiva** [comment]
> > Could I ask you to squash this into one commit?
> 
> @ryjones I am sorry, I did not understand the purpose of it? Will two commits cause any issue in merging?

squashing keeps master history a little cleaner.

**Comment by ajile-in** [comment]
Looks like I messed up with squashing. Sorry, doing it for the first time.

**Comment by ryjones** [comment]
If this has everyone's approval I will do a squash merge

**Comment by ryjones** [comment]
@jadhavajay check out #5 ?

**Review by matt-raffel-kiva — CHANGES_REQUESTED** [review]
I would like to see an issued raised for updating the javascript to ES2015 or ES2016.  I understand this code is just pulled in from indysdk.   I am concerned about community perceptions if we leave this lingering for too long.  I will approve once the issue is written.

**Comment by ajile-in** [comment]
> @jadhavajay check out #5 ?

Yes please.

**Comment by ajile-in** [comment]
> I would like to see an issued raised for updating the javascript to ES2015 or ES2016. I understand this code is just pulled in from indysdk. I am concerned about community perceptions if we leave this lingering for too long. I will approve once the issue is written.

Trying to create an issue for this, but it looks like Issues are not enabled yet. @ryjones can you please help ?

**Review by matt-raffel-kiva — APPROVED** [review]

**Comment by ajile-in** [comment]
@ryjones request you to do a squash merge.

**Comment by ryjones** [comment]
@jadhavajay I think all of this code is merged? https://github.com/hyperledger/aries-sdk-javascript/commit/710eb993f9444f5e3e3ea94142f440f8c6e6bb22

**Pull request merged**
